### ISSUE TITLE
Aufteilung Aufgabe 3

### ISSUE THREAD

**Issue by DayaLuna** [louisap12/Gruppenarbeit-GitHub#1]
Helloo, wir wollten ja die Aufgabe 3 vielleicht aufteilen, damit wir erstmal anfangen und jeder etwas weiterkommt.
Da es bei 3) 6 Teilaufgaben gibt und wir zu fünft sind, würde ich vorschlagen dass jeder eine Teilaufgabe bearbeitet und wir das dann zusammentragen. An der Aufgabe die übrigbleibt können wir dann alle arbeiten.
Sagt gerne mit welcher Teilaufgabe ihr euch zunächst beschäftigen wollt.
Ich mache mal den Anfang mit d)

**Comment by louisap12** [comment]
Hey, das ist eine gute Idee. 👍So können wir das gerne erstmal aufteilen. Ich habe ja schon bei Aufgabe (a) angefangen, die würde ich mir nochmal genau angucken und noch Sachen verbessern. Sonst kann ich auch schon mal die Aufgabe anfangen die übrig geblieben ist.

**Comment by Jessicaa0208** [comment]
Ich würde entweder b) oder e) machen wollen

**Comment by marinaschlueter** [comment]
Ich kann dann c) machen

**Comment by DayaLuna** [comment]
@Minh welche Teilaufgabe willst du machen? f)  hat noch keiner, sonst b) oder e)

**Comment by MKLe3** [comment]
f) kann ich machen und das was über bleibt

**Comment by DayaLuna** [comment]
ok perfekt
