### ISSUE TITLE
Forum für Warnmeldungen

### ISSUE THREAD

**Issue by Jessicaa0208** [louisap12/Gruppenarbeit-GitHub#10]

**Comment by louisap12** [comment]
Ich habe die Warnmeldungen mit if( "Bedungung"){ stop("Warnmeldung") } gemacht, falls das jemandem weiterhilft, ich musste nämlich nochmal kurz nachschauen wie das geht. :)
Dann wird die Funktion gestoppt und gibt die Warnmeldung aus.

**Comment by Jessicaa0208** [comment]
Brauchen wir bei den Funktionen für kategoriellen Variablen auch Warnmeldungen? Weil theoretisch würde das alles ja auch mit Zahlen zum Beispiel funktionieren oder?

**Comment by louisap12** [comment]
Ich glaube bei der max() Funktion könnte es dabei zu Problemen kommen. Aber es stimmt, bei der table() Funktion ist das wahrscheinlich egal.

**Comment by DayaLuna** [comment]
Gibt es eine schönere Möglichkeit zu überprüfen, ob etwas dichotom ist als length(levels(factor(y))) != 2?

**Comment by louisap12** [comment]
Die Idee ist voll gut. Mir würde jetzt spontan nichts besseres einfallen :)

**Comment by marinaschlueter** [comment]
Danke für den Tipp mit der Warnmeldung
