### ISSUE TITLE
Aufgabe 5 (Diskusion)

### ISSUE THREAD

**Issue by MKLe3** [louisap12/Gruppenarbeit-GitHub#15]
Hey Leute hier können wir dann einmal die Ergebnisse besprechen

**Comment by louisap12** [comment]
Danke für das Erstellen 👍  Da wir ja bald mit unserer Auswertung fertig sind, habe ich schon mal versucht eine kleine Zusammenfassung unserer Ergebnisse zu beginnen (nach den Variablen des Datensatzes gegliedert).  Dann ist es bestimmt leichter darüber zu diskutieren.
Ich habe diese unten an unsere Auswertungs- R Datei hinzugefügt.
An alle die gerade daran arbeiten sollen: Guckt gerne schonmal drüber ob alles richtig ist und ergänzt die Sachen die ihr noch rausfindet/hinzufügen wollt. :)

**Comment by DayaLuna** [comment]
Seid ihr mit Aufgabe 4 schon fertig oder wird da noch was ergänzt? Sobald ihr durch seid können Marina und ich euch Aufschluss  darüber geben, welche Schlüsse tatsächlich richtig sind und ggf. das Skript hochladen mit dem wir den Datensatz erstellt haben.

**Comment by Jessicaa0208** [comment]
Wir haben das meiste schon geschafft, wir müssen uns nur noch ein bisschen besprechen und evtl kleinigkeiten verbessern, wir sagen dann bescheid wenn wir fertig sind :)

**Comment by DayaLuna** [comment]
Ok super 👍

**Comment by Jessicaa0208** [comment]
Wir wären jetzt mit Aufgabe 4 fertig, also können wir gerne mit Aufgabe 5 anfangen

**Comment by MKLe3** [comment]
wie läuft das jetzt genau ab? Sagen die beiden uns, was raus kommen sollte und schauen ob das gepasst hat oder wie?

**Comment by louisap12** [comment]
Ich kann ja jetzt schon mal unsere zusammengefassten Ergebnisse hochladen 👍

**Comment by louisap12** [comment]
Hier ist nochmal die Zusammenfassung unserer Ergebnisse (ist aber auch in der R-Datei vorzufinden)

####################################################################################################
# Zusammmenfassung:
####################################################################################################

### 1. Gesamtdatensatz:

#   Allgemein: 
#   (i) Alter:
#    - Durchschnittliches Alter von 25 Jahren (Median)
#    - nahezu Normalverteilung des Alters
#    - Alter liegt zwischen 19 und 30 Jahren
#    -> vgl. a)

#   (ii) Studiengaenge:
#    - Data Science, Informatik, Statistik nahezu gleich haeufig vertreten mit etwa knapp 30%
#    - etwas weniger Mathe Studierende (etwa 15%)
#    -> vgl. a)


#   (iii) Interesse:
#    - etwas mehr Interesse in Programmierung als in Mathe
#    - Beim Mathe-Interesse verteilen sich die beobachteten Realisierungen mehr auf alle Bewertungs-
#      stufen ( vgl. e) )
#    - Beim Interesse in Programmieren ist eine Tendenz zur Linksschiefe erkennbar( vgl. e) )
#    - nahezu kaum Zusammenhaenge zwischen Interesse in Mathe und in Programmieren, sowie 
#      zwischen jeweils beiden Interessen und dem Besuch des Mathe-LKs( vgl. c) & d)  )

#   (iv) Mathe-LK:
#    - etwa 68% haben Mathe-LK besucht, 32% nicht

### 2. Vergleich der Studiengaenge (bzgl. Interessen und Besuch des Mathe-LK)

#   (i) Interessen:
#    - hoechsten Bewertungen Mathe-Interesse: Mathe, Statistik
#    - niedrigsten Bew. Mathe-Interesse: Informatik, Data Science

#    - hoechsten Bew. Programmierungs-Interesse: Informatik, Data Science
#    - niedrigsten Bew. Prog.-Interesse: Mathe, Statistik
#    -> vgl. a), b)

#   (ii) Mathe-LK:
#    - haeufiger bei Mathe, Statistik 
#    - ausgeglichen bei Data Science, Informatik
#    -> vgl. a) (ii)

## Fazit: Es lassen sich nahezu keine Zusammenhaenge zwischen den verschiedenen Interessen oder den
#         Interessen und dem Mathe-LK machen.
#         Jedoch liegen deutliche Unterschiede bei Betrachtung der verschiedenen Studiengaenge bezueglich
#         der verschiedenen Interessen vor.

**Comment by louisap12** [comment]
Tut mir leid, eigentlich wollte ich das nicht so groß machen, dass ist von selbst passiert. Ich hoffe es ist trotzdem hilfreich.

**Comment by MKLe3** [comment]
Okay , dann bin ich mal gespannt, ob das richtig ist was wir raus haben, oder ob  die Ergebnisse sogar was anderes ergeben haben XD

**Comment by DayaLuna** [comment]
Ich habe jetzt unter Github Gruppenarbeit A1.R die "Auflösung" hochgeladen, dann könnt ihr euch selbst anschauen was wir eigentlich gemacht haben.
Aber ich fange schon mal auf eure Ergebnisse einzugehen. 
Normalverteiltes Alter um 25 ist richtig👍 In dem Auswertungsskript hattet ihr auch eine Standardabweichung von 2.1 raus was gut passt, weil wir diese als 2 festgelegt haben.

**Comment by DayaLuna** [comment]
Und bei dem Mathe-LK habt ihr den größten Unterschied auch festgestellt, nämlich dass dieser von Studierenden von Mathe und Statistik häufiger belegt wurde (hatten beabsichtigt Wahrscheinlichkeit dafür bei 80% zu haben) und bei Informatik ausgeglichen.
Für Data Science hattet ihr auch raus, dass der Besuch ausgeglichen war. Eigentlich sollten hier 60% den LK belegt haben, aber das ist wieder untergegangen.

**Comment by louisap12** [comment]
Danke für deine schnelle Rückmeldung, ich habe gerade auch schon mal kurz angeschaut wie ihr den Datensatz erstellt habt und wie unsere Ergebnisse dazu passen .
Insgesamt scheint ja ein Großteil, wie von euch geplant, auch bei den Auswertungen heraus gekommen zu sein. 👍  Was die verschiedenen Verteilungen angeht, hätten wir vielleicht die Funktionen aus e) und f) noch auf die Teildatensätze anwenden können. Dann hätten wir die Gleichverteilung des Interesses der einzelnen Studiengänge vielleicht besser herausarbeiten können.

Erstmal zu der Verteilung des Mathe-Interesses (aus deinem 2.Beitrag):
Mit "das Mathe-Interesse verteilt sich mehr auf allen Bewertungsstufen"  ist glaub ich eher gemeint das sich die Ausprägungen (aller Studiengänge) der Variable Int.Mathe gleichmäßiger auf 1 bis 7 verteilen (also quasi gleichverteilt). Das heißt es ist nicht das Interesse der Mathe Studenten sondern das Interesse an Mathe gemeint (das war vielleicht etwas undeutlich formuliert). Da es weniger Mathe Studenten im Datensatz gibt, entsteht  dann wahrscheinlich keine linksschiefe Verteilung, sondern eine eher gleichverteilte . Linksschiefe hätte man dann nur, wenn es viele/mehr Mathematiker im Datensatz gäbe (vgl.  Funktion(e): tendenziell linksschiefe Verteilung Programmierinteresse + großer Anteil Informatiker mit großem Programmierinteresse).
Daher würde ich sagen, dass die Auswertungen sich nicht mit eurer Erstellung des Datensatz widersprechen. Das größere Interesse an Mathe, dass ihr Mathestudenten gegeben habt, geht aufgrund des kleinen Anteils an Mathestudenten kaum in die Gesamtverteilungen der Variable Int.Mathe ein.

**Comment by louisap12** [comment]
> Ich habe jetzt unter Github Gruppenarbeit A1.R die "Auflösung" hochgeladen, dann könnt ihr euch selbst anschauen was wir eigentlich gemacht haben. Aber ich fange schon mal an auf eure Ergebnisse einzugehen. Normalverteiltes Alter um 25 ist richtig👍 In dem Auswertungsskript hattet ihr auch eine Standardabweichung von 2.1 raus was gut passt, weil wir diese als 2 festgelegt haben.

Das stimmt, das mit der Normalverteilung hat man sehr gut erkennen können. Aber es ist wirklich erstaunlich, dass auch die Standardabweichung so gut dazu passt. 👍

**Comment by DayaLuna** [comment]
> Erstmal zu der Verteilung des Mathe-Interesses (aus deinem 2.Beitrag):
> Mit "das Mathe-Interesse verteilt sich mehr auf allen Bewertungsstufen" ist glaub ich eher gemeint das sich die Ausprägungen (aller Studiengänge) der Variable Int.Mathe gleichmäßiger auf 1 bis 7 verteilen (also quasi gleichverteilt). Das heißt es ist nicht das Interesse der Mathe Studenten sondern das Interesse an Mathe gemeint (das war vielleicht etwas undeutlich formuliert). Da es weniger Mathe Studenten im Datensatz gibt, entsteht dann wahrscheinlich keine linksschiefe Verteilung, sondern eine eher gleichverteilte . Linksschiefe hätte man dann nur, wenn es viele/mehr Mathematiker im Datensatz gäbe (vgl. Funktion(e): tendenziell linksschiefe Verteilung Programmierinteresse + großer Anteil Informatiker mit großem Programmierinteresse).
> Daher würde ich sagen, dass die Auswertungen sich nicht mit eurer Erstellung des Datensatz widersprechen. Das größere Interesse an Mathe, dass ihr Mathestudenten gegeben habt, geht aufgrund des kleinen Anteils an Mathestudenten kaum in die Gesamtverteilungen der Variable Int.Mathe ein.

Ahh ok, so ergibt das Sinn, hatte ich etwas falsch verstanden

**Comment by Jessicaa0208** [comment]
> > Ich habe jetzt unter Github Gruppenarbeit A1.R die "Auflösung" hochgeladen, dann könnt ihr euch selbst anschauen was wir eigentlich gemacht haben. Aber ich fange schon mal an auf eure Ergebnisse einzugehen. Normalverteiltes Alter um 25 ist richtig👍 In dem Auswertungsskript hattet ihr auch eine Standardabweichung von 2.1 raus was gut passt, weil wir diese als 2 festgelegt haben.
> 
> Das stimmt, das mit der Normalverteilung hat man sehr gut erkennen können. Aber es ist wirklich erstaunlich, dass auch die Standardabweichung so gut dazu passt. 👍

Ja das ist mir auch aufgefallen👍

**Comment by Jessicaa0208** [comment]
> Bei den Häufigkeiten der Studiengänge sind eure Erkenntnisse auch gut. Informatik hätte vielleicht etwas selten vorkommen sollen als Statistik und Data Science, aber da wir aus dem Vektor mit Studiengängen mit Wiederholung gezogen haben ist dieser Unterschied untergegangen. Das Interesse an Mathe sollte bei allen außer Mathe-Studierenden gleichverteilt zwischen den 7 Stufen sein und nur bei diesen eher hoch sein. Genauso sollte das Interesse an Programmieren bei allen außer Informatik-Studierenden gleichverteilt zwischen den 7 Stufen sein und nur bei diesen eher hoch sein (und zwar genauso verteilt wie Mathe-Interesse bei Mathematikern). Zwischen den beiden Interessen haben wir nicht versucht einen Zusammenhang zu bilden, das stimmt so. Dass ihr höheres Interesse an Programmieren festgestellt habt ergibt Sinn, da es ja weniger Mathematiker gibt bei denen das Interesse überdurchschnittlich hoch ist. Komisch finde ich aber, dass sich das Mathe-Interesse mehr auf alle Realisierungen verteilt 🤔

Ich finde es auch gut, dass ihr versucht habt den Datensatz so realistisch wie möglich zu gestalten, bzw. Zusammenhänge so zu kreieren, wie man sie tendenziell erwarten oder vermuten würde. Und es freut mich, dass das bei unserer Auswertung auch größtenteils so rauskam👍

**Comment by MKLe3** [comment]
Wow. Okay das meiste hat ja dann geklappt. Der Datensatz hat wirklich gut gepasst und ja ich habe auch gesehen, das mein klein Änderungen an der Funktionen bei uns hätte machen können. Aber im großen und ganzen hatten wir eigentlich ne gute Auswertung

**Comment by louisap12** [comment]
> Und bei dem Mathe-LK habt ihr den größten Unterschied auch festgestellt, nämlich dass dieser von Studierenden von Mathe und Statistik häufiger belegt wurde (hatten beabsichtigt Wahrscheinlichkeit dafür bei 80% zu haben) und bei Informatik ausgeglichen. Für Data Science hattet ihr auch raus, dass der Besuch ausgeglichen war. Eigentlich sollten hier 60% den LK belegt haben, aber das ist wieder untergegangen.

Wenn man die Anteile ausrechnet, kommt man bei Statistik/Mathe Studenten sogar auf eine relative Häufigkeit von über 85% (Mathe sogar etwa 93% ). Bei Data Science käme man auf etwa 46%  und bei Informatik auf etwa 59% .
 Also wurden eigentlich alle von euch vorgesehenen Wahrscheinlichkeiten etwas übertroffen, lediglich bei Data Science ist es genau anders herum. Aber die grobe Richtung scheint wirklich bei allen (bis auf Data Science) zu stimmen.

**Comment by marinaschlueter** [comment]
Das wichtigste habt ihr ja bereits erwähnt. Ich habe mir die Ergebnisse jetzt mal genauer angeguckt und finde es auch ziemlich gut, wie es mit unserer Erstellung des Datensatzes zusammenpasst.

**Comment by Jessicaa0208** [comment]
Ich muss aber auch sagen dass ich am Anfang etwas erstaunt und verwirrt war, als bei den Funktionen c) und d) so gut wie keine Korrelationen rauskamen. Grade bei der Betrachtung von Interesse an Mathe und Wahl von Mathe-LK hatte ich einen Zusammenhang erwartet.

**Comment by DayaLuna** [comment]
> Ich muss aber auch sagen dass ich am Anfang etwas erstaunt und verwirrt war, als bei den Funktionen c) und d) so gut wie keine Korrelationen rauskamen. Grade bei der Betrachtung von Interesse an Mathe und Wahl von Mathe-LK hatte ich einen Zusammenhang erwartet.

Hier hätten wir vielleicht paar mehr Zusammenhänge einbauen können damit die Auswertung spannender ist, aber gut dass man darauf gekommen ist dass es keinen gab :)
Sonst waren insgesamt die Funktionen aus a) und b) am wichtigsten und damit sind die meisten Ergebnisse erzeugt worden.

**Comment by DayaLuna** [comment]
Ich glaube wir wären jetzt mit der Aufgabe fertig oder?
Falls keiner was zu ergänzen hat würde ich das Issue schließen

**Comment by louisap12** [comment]
Ich habe auch nichts mehr hinzuzufügen. Wenn das für alle anderen okay ist, wäre ich auch dafür das Issue zu schließen 👍

**Comment by marinaschlueter** [comment]
Da ich auch nichts weiteres konstruktives gefunden habe, finde ich, dass wir das Issue schließen und die Aufgabe beenden können.

**Comment by MKLe3** [comment]
Bei mir genau so. Bin zu frieden damit und habe nichts zu zufügen. Wir können die Arbeit denke ich beenden

**Comment by Jessicaa0208** [comment]
Ja sehe ich auch so

**Comment by DayaLuna** [comment]
Ok, dann sind wird jetzt fertig🎉
