### ISSUE TITLE
Forum für geeignete deskriptive Statistiken

### ISSUE THREAD

**Issue by louisap12** [louisap12/Gruppenarbeit-GitHub#3]
Vielleicht wäre es gut, wenn wir uns über die Statistiken austauschen die wir benutzen, damit wir nichts wichtiges vergessen.
Für die metrischen Variablen habe ich ja bereits folgende genutzt:
Arithmetische Mittel, Median, Varianz, Standardabweichung, Quartile

**Comment by Jessicaa0208** [comment]
Für kategoriale Variablen habe ich bis jetzt Maximum, Minimum und Spannweite. Wäre aber vielleicht nicht schlecht, wenn wir auch dafür noch mehr finden.

**Comment by MKLe3** [comment]
Ich glaub dafür gibt es nicht viel mehr

**Comment by DayaLuna** [comment]
Bei den kategorialen könnte man noch den Modus berechnen.

**Comment by DayaLuna** [comment]
Zu bivariaten Statistiken schlage ich Korrelation, Kovarianz vor. Zudem könnte man ein einfaches lineares Modell berechnen, das könnte bei der Visualisierung nützlich sein.
