### ISSUE TITLE
Weitere Fuktionen

### ISSUE THREAD

**Issue by Jessicaa0208** [louisap12/Gruppenarbeit-GitHub#4]
Hier können wir Ideen für weitere geeignete Funktionen sammeln.

**Comment by Jessicaa0208** [comment]
Eventuell könnte man auch Visualisierungen für metrische Variablen erstellen

**Comment by DayaLuna** [comment]
Das klingt sinnvoll, könnte man auch für dichotome Variablen ergänzen. 3 f) ist ja nur Visualisierung von kategoriellen Variablen.
